# @package _global_
defaults:
  - override /backend: gpu
  - _self_

deploy_paths:
  data:
    dclm_filter_8k: /scratch/sl12886/data2/llama3-dclm-filter-8k/llama3-dclm-filter-8k/data.zarr/
    books3:  /scratch/sl12886/data2/llama3-books3/llama3-books3/data.zarr/
  checkpoint: ${training.checkpoint_path}

backend:
  distributed: false
  num_processes: 1
  process_id: 0
  num_devices: 1

hydra:
  mode: RUN
  launcher:
    _target_: hydra._internal.core_plugins.basic_launcher.BasicLauncher
